version: '3.8'

services:
  database:
    container_name: go-db
    image: postgres:16.0-alpine3.18
    network_mode: bridge
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: go-server
    network_mode: bridge
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"
    links:
      - database
volumes:
  data: