version: '3.8'

services:
  database:
    #container_name: go-db
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    #container_name: go-server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "3000:3000"
volumes:
  data: